apiVersion: v1
kind: Service
metadata:
  name: crack-dbeaver-password
  labels:
    app: crack-dbeaver-password
spec:
  type: ClusterIP
  ports:
    - port: 18080
      protocol: TCP
      targetPort: 8080
  selector:
    app: crack-dbeaver-password
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: crack-dbeaver-password
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: crack-dbeaver-password
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: crack-dbeaver-password
    spec:
      containers:
        - name: crack-dbeaver-password
          image: geekyouth/crack-dbeaver-password:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "512m"
            limits:
              memory: "2048Mi"
              cpu: "1"
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
