# https://stackoverflow.com/questions/61388905/github-action-to-maven-build-followed-by-docker-build-push
# https://zhuanlan.zhihu.com/p/90122357

name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image on dev
      run: >-
        sudo apt-get install -y maven;
        export APP_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)-snapshot-$(date +%Y%m%d);
        docker login -u geekyouth -p ${{ secrets.DOCKER_CI_TOKEN }};
        docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:${APP_VERSION};
        docker build . -f Dockerfile -t geekyouth/crack-dbeaver-password:latest-snapshot;
        docker push geekyouth/crack-dbeaver-password:${APP_VERSION};
        docker push geekyouth/crack-dbeaver-password:latest-snapshot;
